solutions for 03-objects-arrays-intro-to-testing
js-tasks-ru/js-20210427_artur-mingazhov pull request #3
Opened 2021-05-06 06:32 UTC by Arthur-Ming

2021-05-06 06:32 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-06 11:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      const props = path.split('.')
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-05-06 11:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +         return f(obj[props.shift()])
good 👍   за рекурсию но есть проблема! Представьте что мы создали геттер:
```
const getter = createGetter('foo.bar');
```
а после вызываем его с разными объектами:
```
getter({foo: 1});
getter({bar: { bar: 2 }});
```
`props.shift` изменит "смутирует" переменную `props` что приведет к неожиданному результату для последующих вызовов `getter`

2021-05-06 11:26 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return Object.entries(obj).reduce((result, [key, value]) => {
good 👍  reduce тоже подойдет

2021-05-06 11:26 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +   //return Array.from(new Set(arr))
подумайте в каких случаях лучше использовать `from`

2021-05-06 11:27 UTC, dosandk requested changes
необходимо внести правки в `createGetter`, также подумайте как поправить рекурсивное решение

2021-05-07 06:36 UTC, Arthur-Ming commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +   //return Array.from(new Set(arr))
Как я понял,
Spread работает только с объектами, 
которые итерируемы (String, Array, TypedArray, Map и Set итерируемы, так как их прототипы содержат @@iterator метод,
а Object нет, так как прототип Object не содержит метода @@iterator ).

Array.from() может работать и с Object, если есть свойство length и индексированные элементы 
(массивоподобный объект)

2021-05-10 19:19 UTC, dosandk approved these changes

2021-05-10 19:19 UTC, merged