Solutions
js-tasks-ru/js-20210427_artur-mingazhov pull request #4
Opened 2021-05-16 05:39 UTC by Arthur-Ming

2021-05-16 05:39 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-17 08:35 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +   static isActive = false;
👍 like за статическое свойство

2021-05-17 08:35 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +   show(elem = document.body) {
👍 за дефолтное значение аргумента

2021-05-17 08:37 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +         document.querySelector('.notification').remove();
от обращения к `document` необходимо избавиться. Подумайте, можно ли использовать статическое свойство для такой проверки?

2021-05-17 08:37 UTC, dosandk requested changes
посмотрите комментарии, сделайте правки

2021-05-20 10:12 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      document.body.removeEventListener('pointerover', this.onPointerOver)
good 👍

2021-05-20 10:12 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      target.addEventListener('pointermove', this.onPointerMove)
good 👍

2021-05-20 10:15 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    let result = '';
предпочтительней использовать `map` с приведением к строке через `join('')` вместо конкатенации строк

2021-05-20 10:16 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    const compare = {
good 👍

2021-05-20 10:19 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      //this.element = null
не оставляйте закоментированный код - это плохая практика

2021-05-20 10:19 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +export default class Tooltip {
снятие/добавление обработчиков событий - good 👍

2021-05-20 10:20 UTC, dosandk approved these changes
решения приняты, посмотрите пожалуйста комменты

2021-05-20 10:21 UTC, merged